# These are supported funding model platforms

github: # GitHub Sponsors
  - archilodishelidze

patreon: # Replace with a single Patreon username
  # - yourpatreon

open_collective: # Replace with a single Open Collective username
  # - cryptotrade

ko_fi: # Replace with a single Ko-fi username
  # - cryptotrade

tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
  # - npm/cryptotrade

community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
  # - cryptotrade

liberapay: # Replace with a single Liberapay username
  # - cryptotrade

issuehunt: # Replace with a single IssueHunt username
  # - cryptotrade

otechie: # Replace with a single Otechie username
  # - cryptotrade

lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
  # - cryptotrade

custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
  # - https://www.buymeacoffee.com/cryptotrade
  # - https://paypal.me/cryptotrade
