# These are supported funding model platforms

github: # GitHub Sponsors
  # - archilodishelidze   # enable this only after you join GitHub Sponsors

patreon:
  # - yourpatreon

open_collective:
  # - cryptotrade

ko_fi:
  # - cryptotrade

tidelift:
  # - npm/cryptotrade

community_bridge:
  # - cryptotrade

liberapay:
  # - cryptotrade

issuehunt:
  # - cryptotrade

otechie:
  # - cryptotrade

lfx_crowdfunding:
  # - cryptotrade

custom:
  - https://paypal.me/Odishelidze
