"""Initial migration

Revision ID: 86a4c2890ea2
Revises: 
Create Date: 2025-11-24 14:22:48.969508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a4c2890ea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('is_token', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_deposit', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('min_withdrawal', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('withdrawal_fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('confirmations_required', sa.Integer(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_symbol'), ['symbol'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('kyc_level', sa.Integer(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('locked', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('total', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('available >= 0', name='check_available_positive'),
    sa.CheckConstraint('locked >= 0', name='check_locked_positive'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency_id', name='unique_user_balance')
    )
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balances_user_id'), ['user_id'], unique=False)

    op.create_table('blacklisted_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_addresses_address'), ['address'], unique=True)

    op.create_table('kyc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_expiry', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('margin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collateral', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('borrowed', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('interest_accrued', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('margin_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('max_leverage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('system_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('wallet_type', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=True)

    op.create_table('trading_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.Column('quote_currency_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_margin_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_order_size', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('max_order_size', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('amount_precision', sa.Integer(), nullable=True),
    sa.Column('maker_fee', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('taker_fee', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('high_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('low_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['quote_currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_pairs_symbol'), ['symbol'], unique=True)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency_id', name='unique_user_currency')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=False)

    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_pair_id', 'timeframe', 'timestamp', name='unique_candle')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('idx_candle_lookup', ['trading_pair_id', 'timeframe', 'timestamp'], unique=False)

    op.create_table('fee_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('trading_pair_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_request_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_request_id'], ['kyc_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('margin_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('margin_account_id', sa.Integer(), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('is_liquidated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['margin_account_id'], ['margin_accounts.id'], ),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('filled_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('fee_currency_id', sa.Integer(), nullable=True),
    sa.Column('is_margin', sa.Boolean(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['fee_currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['margin_account_id'], ['margin_accounts.id'], ),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('wallet_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('derivation_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_addresses_address'), ['address'], unique=True)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_pair_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('counter_order_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('total', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('buyer_fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('seller_fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('maker_order_id', sa.Integer(), nullable=False),
    sa.Column('taker_order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['counter_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['maker_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taker_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trading_pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_trading_pair_id'), ['trading_pair_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('to_address', sa.String(length=255), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requires_manual_approval', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('is_blacklisted_address', sa.Boolean(), nullable=True),
    sa.Column('two_factor_verified', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_user_id'))

    op.drop_table('withdrawal_requests')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_trading_pair_id'))
        batch_op.drop_index(batch_op.f('ix_trades_created_at'))

    op.drop_table('trades')
    with op.batch_alter_table('wallet_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_addresses_address'))

    op.drop_table('wallet_addresses')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    op.drop_table('margin_positions')
    op.drop_table('kyc_documents')
    op.drop_table('fee_configs')
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('idx_candle_lookup')

    op.drop_table('candles')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))

    op.drop_table('wallets')
    op.drop_table('user_profiles')
    with op.batch_alter_table('trading_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_pairs_symbol'))

    op.drop_table('trading_pairs')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    op.drop_table('system_wallets')
    op.drop_table('system_settings')
    op.drop_table('margin_accounts')
    op.drop_table('kyc_requests')
    with op.batch_alter_table('blacklisted_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_addresses_address'))

    op.drop_table('blacklisted_addresses')
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balances_user_id'))

    op.drop_table('balances')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_symbol'))

    op.drop_table('currencies')
    # ### end Alembic commands ###
